import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import {
  Box,
  Text,
  Heading,
  Flex,
  Link,
  List,
  ListItem,
} from "@chakra-ui/react";
import { useMe } from "../lib/hooks";

const Home: NextPage = () => {
  const { user, isError, isLoading } = useMe();

  if (isError) {
    return <h2>Something went wrong</h2>;
  }

  return (
    <Box>
      <Head>
        <title>Bookshelfy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Flex flexDirection="column">
          <Heading>Bookshelfy</Heading>
          <Box my={10}>
            {isLoading && <Text>...</Text>}
            {user && <Heading size="md">Welcome {user.firstName}</Heading>}
            <Box mt="10">
              <List>
                <ListItem>
                  <NextLink href="/bookshelf/all">
                    <Link color="teal.500">View all bookshelves</Link>
                  </NextLink>
                </ListItem>
                <ListItem>
                  <NextLink href="/bookshelf/add-book">
                    <Link color="teal.500">Add a new book</Link>
                  </NextLink>
                </ListItem>
                <ListItem>
                  <NextLink href="/authors/add">
                    <Link color="teal.500">Add a new author</Link>
                  </NextLink>
                </ListItem>
              </List>
            </Box>
          </Box>
        </Flex>
      </Box>
    </Box>
  );
};

export default Home;
